# Generated by Django 4.2.1 on 2023-06-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='TypeNoticeId',
        ),
        migrations.RemoveField(
            model_name='users',
            name='TypeUserId',
        ),
        migrations.AddField(
            model_name='noticias',
            name='NoticiaTypeId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='UserTypeID',
            field=models.IntegerField(default=0),
        ),
    ]
