# Generated by Django 4.2.1 on 2023-06-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_noticias_noticiastate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticias',
            old_name='NoticiaDirection',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='NoticiaDate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='NoticiaDay',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='NoticiaAuthor',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='NoticiaId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='NoticiaNumber',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='NoticiaState',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='NoticiaDescription',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='NoticiaTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='NoticiaTypeId',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='NoticiaUrgent',
            new_name='urgent',
        ),
    ]
