# Generated by Django 4.2.1 on 2023-09-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_cajero_citamedica_comprobantecobro_comprobantepago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='cajero',
            name='telefono',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='telefono',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
